name: pytorch-1.13
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - bottleneck=1.3.4
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2023.11.17
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - cryptography=41.0.3
  - freetype=2.11.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - h5py=3.6.0
  - hdf5=1.10.6
  - idna=3.4
  - intel-openmp=2020.2
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - libedit=3.1.20210910
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - ncurses=6.3
  - nettle=3.7.3
  - numexpr=2.7.3
  - numpy=1.19.2
  - numpy-base=1.19.2
  - openh264=2.1.1
  - openssl=1.1.1w
  - packaging=23.1
  - pandas=1.4.2
  - pillow=9.0.1
  - pip=23.3.1
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.8.0
  - python-dateutil=2.8.2
  - pytz=2023.3.post1
  - readline=7.0
  - requests=2.31.0
  - scipy=1.6.2
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.33.0
  - tk=8.6.12
  - tqdm=4.65.0
  - typing_extensions=4.7.1
  - urllib3=1.26.18
  - wheel=0.41.2
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.8.1.2
  - libcurand=10.3.4.101
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - ffmpeg=4.3
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - pip:
    - absl-py==2.1.0
    - accelerate==0.25.0
    - asttokens==2.4.1
    - astunparse==1.6.3
    - backcall==0.2.0
    - brotli==1.0.9
    - cachetools==2.0.0
    - clean-fid==0.1.35
    - contextlib2==0.6.0.post1
    - cycler==0.12.1
    - dataclasses==0.6
    - decorator==5.1.1
    - diffusers==0.24.0
    - einops==0.8.1
    - exceptiongroup==1.2.2
    - executing==2.0.1
    - filelock==3.13.1
    - fsspec==2023.12.2
    - future==0.18.3
    - gast==0.3.3
    - google-auth==1.6.3
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.1.8
    - grpcio==1.24.3
    - huggingface-hub==0.20.1
    - importlib-metadata==7.0.1
    - importlib_resources==6.4.0
    - ipdb==0.13.13
    - ipython==7.31.1
    - jedi==0.19.1
    - joblib==1.4.2
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.4
    - llvmlite==0.39.1
    - markdown==2.6.8
    - markupsafe==2.1.5
    - mat73==0.62
    - matplotlib==3.4.3
    - matplotlib-inline==0.1.7
    - ml-collections==0.1.1
    - monai==1.3.2
    - nibabel==5.2.1
    - ninja==1.11.1.1
    - numba==0.56.4
    - oauthlib==0.6.2
    - opencv-python==4.8.1.78
    - opt-einsum==2.3.2
    - parso==0.8.4
    - pexpect==4.9.0
    - pickleshare==0.7.5
    - prompt_toolkit==3.0.47
    - protobuf==4.25.1
    - psutil==5.9.7
    - ptyprocess==0.7.0
    - pure_eval==0.2.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.1
    - pygments==2.18.0
    - pyparsing==2.4.7
    - pywavelets==1.4.1
    - pyyaml==6.0.1
    - regex==2023.12.25
    - requests-oauthlib==0.7.0
    - rsa==3.1.4
    - safetensors==0.4.1
    - scikit-learn==1.0.2
    - sigpy==0.0.8
    - stack-data==0.6.3
    - tensorboard==2.3.0
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.6.2.2
    - tensorflow==2.3.1
    - tensorflow-estimator==2.3.0
    - termcolor==1.1.0
    - threadpoolctl==3.5.0
    - timm==0.9.12
    - tomli==2.0.1
    - torch==1.10.2+cu113
    - traitlets==5.14.3
    - wcwidth==0.2.13
    - werkzeug==3.0.3
    - wrapt==1.11.1
    - zipp==3.17.0

